services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tribe-separator
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./database:/var/www/html/database
